### ISSUE TITLE
Docs for usage with templates

### ISSUE THREAD

**Issue by rogierlommers** [mjibson/esc#12]
I'm using the `/text/template` package for html rendering. Now I want to use `esc` for including the templates files in my binary. I'm looking for a good example, but I can't find it. Is there a way to access a file from the generated sources as an asset which will be accepted by the template.-functions?

	tmpl, parseErr := template.ParseFiles(baseFile, headerFile, footerFile)
	if parseErr != nil {
		http.Error(w, parseErr.Error(), http.StatusInternalServerError)
		return
	}

	if templErr := tmpl.Execute(w, renderObject); templErr != nil {
		http.Error(w, templErr.Error(), http.StatusInternalServerError)
	}

**Comment by mjibson** [comment]
```
str := FSMustString(devMode, "/templates/index.html")
template, err := template.New("").Parse(str)
```

**Comment by rogierlommers** [comment]
Thanks; working fine.
