### ISSUE TITLE
ModTime from PR #13 changes static.go and Tsc files every build

### ISSUE THREAD

**Issue by gbrayut** [mjibson/esc#15]
The ModTime feature added in #13 causes our CI builds to fail due to the timestamps changing and causing our checks to think that the static.go and Tsc generated bosun.js file are out of date. I don't believe git syncs the last modified date, so anyone using multiple systems or having multiple contributors is likely to have the same issue.

Initially after we updated to the new version of esc (see https://github.com/bosun-monitor/bosun/pull/1307 ) I though it was just an issue with TypeScript, but after ensuring it only updates the .js file when the content changes (see https://github.com/bosun-monitor/bosun/pull/1308 ) we are still seeing issues with our CI builds.

I don't think we need the ModTime feature, so having a flag to disable it would meet our needs. @captncraig or I can probably create a PR to disable ModTime (or enable it if you want it disabled by default)

**Comment by mjibson** [comment]
Understood. go-bindata has a modtime option to set this. I'll add that tonight. It'll look like this:

https://github.com/jteeuwen/go-bindata/blob/bfe36d3254337b7cc18024805dfab2106613abdf/go-bindata/main.go#L52

Is that ok?

**Comment by gbrayut** [comment]
Yep... then we can add -modtime 0 to our go generate calls and it should fix the issue.

Thanks!
