### ISSUE TITLE
Version number and CLI option

### ISSUE THREAD

**Issue by sabhiram** [mjibson/esc#22]
Awesome project that we use daily! One thing we do with `go generate` is to invoke esc as part of our code generation step to bundle the assets and whatnot into a few "static.go"esq files. It would be very useful to be able to query the version of esc to validate its existence before attempting to use it.

**Comment by mjibson** [comment]
I'm not sure what problem this is solving. What does "query the version of esc to validate its existence" mean?

**Comment by sabhiram** [comment]
You are right, it does not really solve anything. I check `esc's` existence in our build slaves via whatever scripting env I have.
