### ISSUE TITLE
How does this differ from other similar projects?

### ISSUE THREAD

**Issue by shurcooL** [mjibson/esc#26]
Hi there,

I just discovered this project. I have a similar one called [`vfsgen`](https://github.com/shurcooL/vfsgen), that also generates a .go file that implements `http.FileSystem` and only uses standard library.

In its README, I have a [list of alternatives](https://github.com/shurcooL/vfsgen#comparison) because I [think it's a good idea](https://github.com/shurcooL/vfsgen/pull/6#issue-107431054), and I'd like to add your project there. Can you help me understand in what ways this project is unique, what does it focus on/optimize for, and what would be a good description?

Thanks!

**Comment by shurcooL** [comment]
I've found https://mattjibson.com/blog/2014/11/19/esc-embedding-static-assets/, which helps answer this question somewhat. Unfortunately, I don't see `vfsgen` in the comparison there, I wonder how it would stack up for the needs you specified.

That post is from late 2014, and `vfsgen` has only been around for 6-12 months or so, which explains why you couldn't have listed it there.

**Comment by mjibson** [comment]
Yes, feel free to add esc if you like. It looks pretty similar but a bit different than vfsgen, which is nice. From first looks I think vfsgen has some features esc doesn't. I like that vfsgen also generates its own go:generate script instead of relying on itself being installed. That's slick and an improvement over esc.

**Comment by shurcooL** [comment]
Done in https://github.com/shurcooL/vfsgen/commit/86c691e18a3285e15928cd40192fd8ca3648a3a3. Thanks!
