### ISSUE TITLE
generated code do not satisfy go lint

### ISSUE THREAD

**Issue by sekimura** [mjibson/esc#9]
static.go:14:6: don't use underscores in Go names; type _esc_localFS should be _escLocalFS
static.go:16:5: don't use underscores in Go names; var _esc_local should be _escLocal
static.go:18:6: don't use underscores in Go names; type _esc_staticFS should be _escStaticFS
static.go:20:5: don't use underscores in Go names; var _esc_static should be _escStatic
static.go:22:6: don't use underscores in Go names; type _esc_file should be _escFile
static.go:166:5: don't use underscores in Go names; var _esc_data should be _escData

**Comment by jacobhaven** [comment]
This is a serious problem. In order to use this tool, [I've needed to manually edit the names](https://github.com/cloudflare/cfssl/commit/2994ff383dce502a43f8f95d4efc94e129a0fbaf) that don't correspond to Go style.

**Comment by sekimura** [comment]
Thanks for making the change! :+1:
